/*
 * Projekt ITU
 * Výukový program na znalost ptáků
 * Hlavni okno obsahujici jednotlive obrazovky
 * a funkce pro jejich rizeni
 * 
 */
package birds;

/**
 *
 * @author Lukas
 */
public class Birds extends javax.swing.JFrame {

    /**
     * Creates new form Birds
     */
    public Birds() {
        super();
        initComponents();
        
        //Zneviditelnovani ostatnich oken
        this.hlavniMenu.setVisible(false);
        this.regObrazovka.setVisible(false);
        this.vyberTestuObrazovka.setVisible(false);
        this.klasickyTestObrazovka.setVisible(false);
        ////////////////////////////////////////////////////
        
        //Pridavani odkazu na okno jednotlivym obrazovkam
        this.hlavniMenu.addFrame(this);
        this.prihlObrazovka.addFrame(this);
        this.regObrazovka.addFrame(this);
        this.vyberTestuObrazovka.addFrame(this);
        this.klasickyTestObrazovka.addFrame(this);
        ////////////////////////////////////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vrstva = new javax.swing.JLayeredPane();
        prihlObrazovka = new birds.screens.LoginSreen();
        regObrazovka = new birds.screens.RegistrationScreen();
        hlavniMenu = new birds.screens.MainMenu();
        vyberTestuObrazovka = new birds.screens.TestChooseScreen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        prihlObrazovka.setBounds(0, 0, 1100, 700);
        vrstva.add(prihlObrazovka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        regObrazovka.setBounds(0, 0, 1100, 720);
        vrstva.add(regObrazovka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hlavniMenu.setBounds(0, 0, 1000, 700);
        vrstva.add(hlavniMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vyberTestuObrazovka.setBounds(0, 0, 1000, 700);
        vrstva.add(vyberTestuObrazovka, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vrstva, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vrstva, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Birds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Birds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Birds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Birds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Birds b = new Birds();
                b.setVisible(true);
            }
        });
    }
    
    
    /******************************************
     * Funkce pro nastavovani viditelnosti oken
     ******************************************/
    
    public void setHlavniMenuVisible(boolean b) {
        this.hlavniMenu.setVisible(b);
    }

    public void setprihlObrazovkaVisible(boolean b) {
        this.prihlObrazovka.setVisible(b);
    }
    
    public void setregObrazovkaVisible(boolean b) {
        this.regObrazovka.setVisible(b);
    }
    
    public void setvyberTestuObrazovkaObrazovkaVisible(boolean b) {
        this.vyberTestuObrazovka.setVisible(b);
    }
    
    public void setklasickyTestObrazovkaVisible(boolean b) {
        this.klasickyTestObrazovka.setVisible(b);
    }
   /*********************************************/ 
    
    public void setUserName(String name){
        this.UserName = name;
    }
    
    public String getUserName(){
        return this.UserName;
    }
    
    
    
    private String UserName;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private birds.screens.MainMenu hlavniMenu;
    private birds.screens.LoginSreen prihlObrazovka;
    private birds.screens.RegistrationScreen regObrazovka;
    private javax.swing.JLayeredPane vrstva;
    private birds.screens.TestChooseScreen vyberTestuObrazovka;
    // End of variables declaration//GEN-END:variables
}
