/*
 * Projekt ITU
 * Výukový program na znalost ptáků
 * Třída implementujici prihlasovaci obrazovku a jeji obsluhu
 * 
 */
package birds.screens;

import birds.users.UserDatabase;
import birds.graphics.Background;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Lukas
 */
public class loginSreen extends Background {

    /**
     * Creates new form loginSreen
     */
    public loginSreen() {
        super();
        initComponents();
        this.Prihlaseni.setVisible(true);
        this.wrongLogin.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popis = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Prihlaseni = new birds.graphics.loginPanel();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        loginLabel1 = new javax.swing.JLabel();
        loginPass = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        ukoncit = new javax.swing.JButton();
        regButton = new javax.swing.JButton();
        wrongLogin = new birds.graphics.loginPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));

        Popis.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        Popis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Popis.setText("Výukový program na znalost ptáků ČR");
        Popis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Popis.setMaximumSize(new java.awt.Dimension(500, 80));
        Popis.setMinimumSize(new java.awt.Dimension(500, 80));
        Popis.setPreferredSize(new java.awt.Dimension(500, 80));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(300, 400));

        Prihlaseni.setMaximumSize(new java.awt.Dimension(300, 400));
        Prihlaseni.setMinimumSize(new java.awt.Dimension(300, 400));
        Prihlaseni.setOpaque(false);
        Prihlaseni.setPreferredSize(new java.awt.Dimension(300, 400));

        loginLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        loginLabel.setText("Přihlašovací jméno");

        loginField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        loginField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 171, 0), 8));

        loginLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        loginLabel1.setText("Heslo");

        loginPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 171, 0), 8));

        loginButton.setBackground(new java.awt.Color(252, 197, 80));
        loginButton.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        loginButton.setText("Přihlásit");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 171, 0), 8, true));
        loginButton.setFocusable(false);
        loginButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        loginButton.setMaximumSize(new java.awt.Dimension(300, 70));
        loginButton.setMinimumSize(new java.awt.Dimension(300, 70));
        loginButton.setPreferredSize(new java.awt.Dimension(300, 70));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        ukoncit.setBackground(new java.awt.Color(252, 197, 80));
        ukoncit.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        ukoncit.setText("Ukončit");
        ukoncit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 171, 0), 8, true));
        ukoncit.setFocusable(false);
        ukoncit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ukoncit.setMaximumSize(new java.awt.Dimension(300, 70));
        ukoncit.setMinimumSize(new java.awt.Dimension(300, 70));
        ukoncit.setPreferredSize(new java.awt.Dimension(300, 70));
        ukoncit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukoncitActionPerformed(evt);
            }
        });

        regButton.setBackground(new java.awt.Color(252, 197, 80));
        regButton.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        regButton.setText("Vytvořit");
        regButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 171, 0), 8, true));
        regButton.setFocusable(false);
        regButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        regButton.setMaximumSize(new java.awt.Dimension(300, 70));
        regButton.setMinimumSize(new java.awt.Dimension(300, 70));
        regButton.setPreferredSize(new java.awt.Dimension(300, 70));
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrihlaseniLayout = new javax.swing.GroupLayout(Prihlaseni);
        Prihlaseni.setLayout(PrihlaseniLayout);
        PrihlaseniLayout.setHorizontalGroup(
            PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrihlaseniLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(loginPass)
                        .addComponent(loginLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginField))
                    .addGroup(PrihlaseniLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PrihlaseniLayout.createSequentialGroup()
                                .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ukoncit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        PrihlaseniLayout.setVerticalGroup(
            PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrihlaseniLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(loginLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukoncit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Prihlaseni.setBounds(0, 0, 300, 400);
        jLayeredPane1.add(Prihlaseni, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrongLogin.setOpaque(false);
        wrongLogin.setPreferredSize(new java.awt.Dimension(300, 400));
        wrongLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wrongLoginMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Špatně zadaný login, nebo heslo.");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pokud nevlastníte účet, klikněte");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("na tlačítko \"Vytvořit\".");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pro návrat klikněte sem.");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout wrongLoginLayout = new javax.swing.GroupLayout(wrongLogin);
        wrongLogin.setLayout(wrongLoginLayout);
        wrongLoginLayout.setHorizontalGroup(
            wrongLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrongLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrongLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        wrongLoginLayout.setVerticalGroup(
            wrongLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrongLoginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        wrongLogin.setBounds(0, 0, 300, 400);
        jLayeredPane1.add(wrongLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(Popis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Popis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    /*
     * Zmacknuti tlacitka prihlaseni
     * potreba spojit s databazi uzivatelu
     */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        String login = this.loginField.getText();
        String heslo = new String(this.loginPass.getPassword());
        
        try {
            if (UserDatabase.TestPass(login, heslo)) {
                // Zneviditelneni prihlasovaci obrazovky
                this.Okno.setprihlObrazovkaVisible(false);
                
                
                //Vynulovani prihlasovaci obrazovky
                this.loginPass.setText("");
                this.loginField.setText("");
                
                //Zviditelneni hlavniho menu
                this.Okno.setHlavniMenuVisible(true);
            }else{
                // Zneviditelneni panelu prihlaseni
                this.Prihlaseni.setVisible(false);
                
                //Zviditelneni chybove hlasky
                this.wrongLogin.setVisible(true);
            }           
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            Logger.getLogger(loginSreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    /*
     * Tlacitko ukoncit zmacknuto
     * potreba pridelat dotazovani, zda opravdu chceme ukoncit program
     */
    private void ukoncitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukoncitActionPerformed
        this.Okno.dispose();
    }//GEN-LAST:event_ukoncitActionPerformed

    
    /*
     * Tlacitko vytvorti zmacknuto
     */
    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        
        this.Okno.setprihlObrazovkaVisible(false);
        this.Okno.setregObrazovkaVisible(true);
    }//GEN-LAST:event_regButtonActionPerformed

    private void wrongLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrongLoginMouseClicked
        
        //Zviditelneni chybove hlasky
                this.wrongLogin.setVisible(false);
        
        //Vynulovani prihlasovaci obrazovky
                this.loginPass.setText("");
                this.loginField.setText("");
                
        // Zneviditelneni panelu prihlaseni
                this.Prihlaseni.setVisible(true);
                        
    }//GEN-LAST:event_wrongLoginMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Popis;
    private birds.graphics.loginPanel Prihlaseni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JButton regButton;
    private javax.swing.JButton ukoncit;
    private birds.graphics.loginPanel wrongLogin;
    // End of variables declaration//GEN-END:variables
}
