/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package birds.screens;

import birds.users.UserDatabase;
import birds.graphics.Background;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;


/**
 *
 * @author Lukas
 */
public class RegistrationScreen extends Background {

    /**
     * Creates new form RegistrationScreen
     */
    public RegistrationScreen() {
        initComponents();
        this.registrace.setVisible(true);
        this.success.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popis = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        registrace = new birds.graphics.loginPanel();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        loginPass = new javax.swing.JPasswordField();
        regButton = new javax.swing.JButton();
        loginPassAgain = new javax.swing.JPasswordField();
        passLabelAgain = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        success = new birds.graphics.loginPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));

        Popis.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        Popis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Popis.setText("Výukový program na znalost ptáků ČR");
        Popis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Popis.setMaximumSize(new java.awt.Dimension(500, 80));
        Popis.setMinimumSize(new java.awt.Dimension(500, 80));
        Popis.setPreferredSize(new java.awt.Dimension(500, 80));

        registrace.setMaximumSize(new java.awt.Dimension(300, 400));
        registrace.setMinimumSize(new java.awt.Dimension(300, 400));
        registrace.setOpaque(false);

        loginLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        loginLabel.setText("Přihlašovací jméno");

        loginField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        loginField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 171, 0), 8));

        passLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        passLabel.setText("Heslo");

        loginPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 171, 0), 8));

        regButton.setBackground(new java.awt.Color(252, 197, 80));
        regButton.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        regButton.setText("Vytvořit");
        regButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 171, 0), 8, true));
        regButton.setFocusable(false);
        regButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        regButton.setMaximumSize(new java.awt.Dimension(300, 70));
        regButton.setMinimumSize(new java.awt.Dimension(300, 70));
        regButton.setPreferredSize(new java.awt.Dimension(300, 70));
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        loginPassAgain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 171, 0), 8));

        passLabelAgain.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        passLabelAgain.setText("Heslo znovu");

        cancel.setBackground(new java.awt.Color(252, 197, 80));
        cancel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        cancel.setText("Zrušit");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 171, 0), 8, true));
        cancel.setFocusable(false);
        cancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cancel.setMaximumSize(new java.awt.Dimension(300, 70));
        cancel.setMinimumSize(new java.awt.Dimension(300, 70));
        cancel.setPreferredSize(new java.awt.Dimension(300, 70));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registraceLayout = new javax.swing.GroupLayout(registrace);
        registrace.setLayout(registraceLayout);
        registraceLayout.setHorizontalGroup(
            registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registraceLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loginPass)
                    .addComponent(passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(loginField)
                    .addComponent(loginPassAgain)
                    .addComponent(passLabelAgain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registraceLayout.createSequentialGroup()
                        .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        registraceLayout.setVerticalGroup(
            registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registraceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(passLabelAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(loginPassAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(registraceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        registrace.setBounds(0, 0, 300, 410);
        jLayeredPane1.add(registrace, javax.swing.JLayeredPane.DEFAULT_LAYER);

        success.setOpaque(false);
        success.setPreferredSize(new java.awt.Dimension(300, 400));
        success.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                successMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Účet byl úspěšně vytvořen.");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("obrazovku klikněte sem.");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nyní se můžete přihlásit.");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pro návrat na přihlašovací ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout successLayout = new javax.swing.GroupLayout(success);
        success.setLayout(successLayout);
        successLayout.setHorizontalGroup(
            successLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(successLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        successLayout.setVerticalGroup(
            successLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        success.setBounds(0, 0, 300, 400);
        jLayeredPane1.add(success, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(Popis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Popis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        String login = this.loginField.getText();
        String heslo = new String(this.loginPass.getPassword());
        String hesloAgain = new String(this.loginPassAgain.getPassword());
        
        try {
            if (UserDatabase.TestName(login)!=true) {
                if (heslo.equals(hesloAgain)) {
                    try {
                        UserDatabase.AddUser(login,heslo);
                        this.loginPass.setText("");
                        this.loginField.setText("");
                        this.loginPassAgain.setText("");
                        this.registrace.setVisible(false);
                        this.success.setVisible(true);
                        
                    } catch (ParserConfigurationException | SAXException | IOException | TransformerException ex) {
                        Logger.getLogger(RegistrationScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            Logger.getLogger(RegistrationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_regButtonActionPerformed

    
    
    /*
     * Tlacitko zrusit zmacknuto
     */
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.loginPass.setText("");
        this.loginField.setText("");
        this.loginPassAgain.setText("");
        this.Okno.setregObrazovkaVisible(false);
        this.Okno.setprihlObrazovkaVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void successMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_successMouseClicked

        this.success.setVisible(false);
        this.registrace.setVisible(true);
        this.Okno.setregObrazovkaVisible(false);
        this.Okno.setprihlObrazovkaVisible(true);

    }//GEN-LAST:event_successMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Popis;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JPasswordField loginPassAgain;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabelAgain;
    private javax.swing.JButton regButton;
    private birds.graphics.loginPanel registrace;
    private birds.graphics.loginPanel success;
    // End of variables declaration//GEN-END:variables
}
