/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package birds.screens;

import birds.users.UserDatabase;
import birds.graphics.Background;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;


/**
 *
 * @author Lukas
 */
public class RegistrationScreen extends Background {

    /**
     * Creates new form RegistrationScreen
     */
    public RegistrationScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popis = new javax.swing.JLabel();
        Prihlaseni = new birds.graphics.loginPanel();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        loginPass = new javax.swing.JPasswordField();
        regButton = new javax.swing.JButton();
        loginPassAgain = new javax.swing.JPasswordField();
        passLabelAgain = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));

        Popis.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        Popis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Popis.setText("Výukový program na znalost ptáků ČR");
        Popis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Popis.setMaximumSize(new java.awt.Dimension(500, 80));
        Popis.setMinimumSize(new java.awt.Dimension(500, 80));
        Popis.setPreferredSize(new java.awt.Dimension(500, 80));

        Prihlaseni.setMaximumSize(new java.awt.Dimension(300, 400));
        Prihlaseni.setMinimumSize(new java.awt.Dimension(300, 400));
        Prihlaseni.setOpaque(false);

        loginLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        loginLabel.setText("Přihlašovací jméno");

        loginField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        loginField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 171, 0), 8));

        passLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        passLabel.setText("Heslo");

        loginPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 171, 0), 8));

        regButton.setBackground(new java.awt.Color(252, 197, 80));
        regButton.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        regButton.setText("Vytvořit");
        regButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 171, 0), 8, true));
        regButton.setFocusable(false);
        regButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        regButton.setMaximumSize(new java.awt.Dimension(300, 70));
        regButton.setMinimumSize(new java.awt.Dimension(300, 70));
        regButton.setPreferredSize(new java.awt.Dimension(300, 70));
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        loginPassAgain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(251, 171, 0), 8));

        passLabelAgain.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        passLabelAgain.setText("Heslo znovu");

        cancel.setBackground(new java.awt.Color(252, 197, 80));
        cancel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        cancel.setText("Zrušit");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 171, 0), 8, true));
        cancel.setFocusable(false);
        cancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cancel.setMaximumSize(new java.awt.Dimension(300, 70));
        cancel.setMinimumSize(new java.awt.Dimension(300, 70));
        cancel.setPreferredSize(new java.awt.Dimension(300, 70));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrihlaseniLayout = new javax.swing.GroupLayout(Prihlaseni);
        Prihlaseni.setLayout(PrihlaseniLayout);
        PrihlaseniLayout.setHorizontalGroup(
            PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrihlaseniLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loginPass)
                    .addComponent(passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(loginField)
                    .addComponent(loginPassAgain)
                    .addComponent(passLabelAgain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PrihlaseniLayout.createSequentialGroup()
                        .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        PrihlaseniLayout.setVerticalGroup(
            PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrihlaseniLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(passLabelAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(loginPassAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(PrihlaseniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(Popis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(Prihlaseni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Popis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Prihlaseni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        String login = this.loginField.getText();
        String heslo = new String(this.loginPass.getPassword());
        String hesloAgain = new String(this.loginPassAgain.getPassword());
        
        try {
            if (UserDatabase.TestName(login)!=true) {
                if (heslo.equals(hesloAgain)) {
                    try {
                        UserDatabase.AddUser(login,heslo);
                        this.loginPass.setText("");
                        this.loginField.setText("");
                        this.loginPassAgain.setText("");
                        this.Okno.setregObrazovkaVisible(false);
                        this.Okno.setprihlObrazovkaVisible(true);
                        
                    } catch (ParserConfigurationException | SAXException | IOException | TransformerException ex) {
                        Logger.getLogger(RegistrationScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            Logger.getLogger(RegistrationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_regButtonActionPerformed

    
    
    /*
     * Tlacitko zrusit zmacknuto
     */
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.loginPass.setText("");
        this.loginField.setText("");
        this.loginPassAgain.setText("");
        this.Okno.setregObrazovkaVisible(false);
        this.Okno.setprihlObrazovkaVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Popis;
    private birds.graphics.loginPanel Prihlaseni;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JPasswordField loginPassAgain;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabelAgain;
    private javax.swing.JButton regButton;
    // End of variables declaration//GEN-END:variables
}
