/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package birds.screens;

import birds.graphics.Background;

/**
 *
 * @author Lukas
 */
public class StatisticScreen extends Background {

    /**
     * Creates new form StatisticScreen
     */
    public StatisticScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popis = new javax.swing.JLabel();
        TestChooser = new javax.swing.JComboBox();
        StatPanel = new birds.graphics.LessonPanel();
        TestTypeLabel = new javax.swing.JLabel();
        TestIdLabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        TestType = new javax.swing.JLabel();
        TestId = new javax.swing.JLabel();
        difficulty = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        percentLabel = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        mainMenuBut = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1000, 700));

        Popis.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        Popis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Popis.setText("Statistiky");
        Popis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Popis.setMaximumSize(new java.awt.Dimension(500, 80));
        Popis.setMinimumSize(new java.awt.Dimension(500, 80));
        Popis.setPreferredSize(new java.awt.Dimension(500, 80));

        TestChooser.setBackground(new java.awt.Color(251, 171, 0));
        TestChooser.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TestChooser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TestChooserItemStateChanged(evt);
            }
        });

        StatPanel.setOpaque(false);

        TestTypeLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TestTypeLabel.setText("Typ Testu:");

        TestIdLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TestIdLabel.setText("Id Testu:");

        difficultyLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        difficultyLabel.setText("Obtížnost:");

        resultLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        resultLabel.setText("Výsledek:");

        TestType.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        TestType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TestId.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N

        difficulty.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N

        result.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N

        percentLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        percentLabel.setText("Úspěšnost:");
        percentLabel.setPreferredSize(new java.awt.Dimension(140, 23));

        percent.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N

        javax.swing.GroupLayout StatPanelLayout = new javax.swing.GroupLayout(StatPanel);
        StatPanel.setLayout(StatPanelLayout);
        StatPanelLayout.setHorizontalGroup(
            StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatPanelLayout.createSequentialGroup()
                        .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resultLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(difficultyLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(difficulty, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(StatPanelLayout.createSequentialGroup()
                        .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TestTypeLabel)
                            .addComponent(TestIdLabel))
                        .addGap(18, 18, 18)
                        .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TestType, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(TestId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
            .addGroup(StatPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(percentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        StatPanelLayout.setVerticalGroup(
            StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TestTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestType, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TestIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(difficultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(percentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        mainMenuBut.setBackground(new java.awt.Color(252, 197, 80));
        mainMenuBut.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        mainMenuBut.setText("Hlavní menu");
        mainMenuBut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(251, 171, 0), 8, true));
        mainMenuBut.setFocusable(false);
        mainMenuBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(Popis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(TestChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(mainMenuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Popis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TestChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(StatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(mainMenuBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TestChooserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TestChooserItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TestChooserItemStateChanged

    private void mainMenuButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButActionPerformed
        this.Okno.setstatistikyObrazovkaVisible(false);
        this.Okno.setHlavniMenuVisible(true);
    }//GEN-LAST:event_mainMenuButActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Popis;
    private birds.graphics.LessonPanel StatPanel;
    private javax.swing.JComboBox TestChooser;
    private javax.swing.JLabel TestId;
    private javax.swing.JLabel TestIdLabel;
    private javax.swing.JLabel TestType;
    private javax.swing.JLabel TestTypeLabel;
    private javax.swing.JLabel difficulty;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JButton mainMenuBut;
    private javax.swing.JLabel percent;
    private javax.swing.JLabel percentLabel;
    private javax.swing.JLabel result;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
