/*
 * Projekt ITU
 * Výukový program na znalost ptáků
 * Otcovska trida jednotlivych obrazovek
 * obsahuje pozadi a odkaz na hlavni okno
 * 
 */
package birds.graphics;

import java.awt.*;
import javax.swing.*;
import birds.Birds;

/**
 *
 * @author Lukas
 */
public class Background extends javax.swing.JPanel {

    /**
     * Creates new form MainWindow
     */
    protected Birds Okno;

    public Background() {
        super();
        initComponents();

    }
    
    public void addFrame(Birds o){
        this.Okno = o;
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Image bg = new ImageIcon("lib\\background.jpg").getImage();
        g.drawImage(bg, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
